services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
